version: "3.9"
services:
  rabbitmq:
    build: rabbitmq/.
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  inventory:
    build: ./inventory-service
    ports:
      - 5002:5002
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
  data:
    build: ./data-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/

  webhook:
    build: ./webhook-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/

  shipping:
    build: ./shipping-service
    ports:
      - 5001:5001
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
  users:
    build: ./users-service
    ports:
      - 5007:5007
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
    depends_on:
      rabbitmq:
        condition: service_healthy
  billing:
    build: ./billing-service
    ports:
      - 5009:5009
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
